{
 "title": "otf",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(otf_cache_collisions, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "server logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"otf\", namespace=\"default\"} | pattern \"<time> <loglevel> <msg> | <remainder>\" | logfmt | line_format \"{{.loglevel}} {{printf \\\"%-60s\\\" .msg}} {{.remainder}}\""
    },
    { "expr": "1 + 1" }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"ingress-nginx\"} !~\"uptimerobot\" | json | ingress=\"otf\" request_uri !~ \"^/static/.*\" request_uri !~ \"^/favicon.ico\" geoip_country_code != \"\" | __error__=\"\" [$__interval])) by (geoip_country_code)",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"} |~\"^{\" !~\"uptimerobot\" | json | ingress = \"otf\" and request_uri !~ \"^/static/.*\" and request_uri !~ \"^/favicon.ico\" | line_format \"| {{ printf \\\"%-15s\\\" .remote_addr }} {{ .status}} {{ printf \\\"%-4s\\\" .request_method }} {{.request_uri}}\""
    }
   ]
  },
  {
   "title": "Pub Sub",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "otf_pub_sub_queue_length{pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - {{name}} - queue"
    },
    {
     "expr": "otf_pub_sub_total_subscribers{pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - subs"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "otf_cache_collisions{pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - collisions"
    },
    {
     "expr": "otf_cache_entries{pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - entries"
    },
    {
     "expr": "otf_cache_hits{pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - hits"
    },
    {
     "expr": "otf_cache_misses{pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - misses"
    }
   ]
  }
 ]
}